dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      before_install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - export PATH=$HOME/.poetry/bin:$PATH
      install:
        - poetry install
      script:
        - poetry run pytest -sv
